---
- name: Define geocouch_ebin_dir.
  shell: ls -1 {{ couchdb_erl_libs_dir.stdout }}/geocouch/ebin
  register: geocouch_ebin_dir
  changed_when: false
  always_run: yes

- name: Ensure ebin files exists.
  shell: >
    cp -n {{ couchdb_erl_libs_dir.stdout }}/geocouch/ebin/{{ item }} {{ item }}
    chdir={{ couchdb_erl_libs_dir_ebin }}
    creates={{ item }}
  with_items: "{{ geocouch_ebin_dir.stdout_lines }}"
  notify: restart couchdb

- name: Ensure geocouch.ini files exists.
  shell: >
    cp -n {{ couchdb_erl_libs_dir.stdout }}/geocouch/etc/couchdb/default.d/{{ item }} {{ item }}
    chdir={{ geocouch_conf_dir }}
    creates={{ item }}
  with_items:
    - "{{ geocouch_conf_file }}"
  notify: restart couchdb

- name: Set permission.
  file:
    path: "{{ geocouch_conf_dir }}/{{ geocouch_conf_file }}"
    owner: couchdb
    group: couchdb
    mode: 0644
    state: file
  notify: restart couchdb
